version: '3.2'

services:

  users:
    container_name: flask-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_dev  # new
      - DATABASE_TEST_URL=postgresql://postgres:postgres@users-db:5432/users_test  # new
    depends_on:
      - users-db

  users-db:
    container_name: user-db-dev
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
