version: '3.7'

services:

  users:
    container_name: flask-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 6001:6000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_prod  # new
    depends_on:
      - users-db

  users-db:
    container_name: user-db-prod
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
