version: 2
jobs:
  build:
    machine: true
    environment:
      IMAGE: registry.heroku.com/aqueous-mountain-28973/web
    steps:
      - checkout
      # start proprietary DB using private Docker image
      - run:
          name: build docker image
          command: |
              docker login -u $DOCKER_USER -p $DOCKERHUB_PASSWORD
              docker pull $IMAGE:latest || true
              docker build --cache-from $IMAGE:latest --tag $IMAGE:latest --file ./Dockerfile.prod .
              docker push $IMAGE:latest

  test:
    # すべてのコマンドを実行する場所となるプライマリコンテナイメージ
    docker:
      - image: registry.heroku.com/aqueous-mountain-28973/web:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKERHUB_PASSWORD
      # サービスコンテナイメージ
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - checkout
      - run:
          name: Run test and formatter
          environment:
              POSTGRES_DB: users
              POSTGRES_USER: runner
              POSTGRES_PASSWORD: ""
              DATABASE_TEST_URL: postgres://runner@postgres:5432/users
          command: |
              pytest "project/tests" -p no:warnings
              flake8 project
              black project --check
              isort project/**/*.py --check-only

      - setup_remote_docker
