version: 2
jobs:
  build:
    machine: true
    environment:
      IMAGE: registry.heroku.com/young-peak-91678/web
      HEROKU_APP_NAME: young-peak-91678
    steps:
      - checkout

      # build
      - run:
          name: login docker
          command: docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
      - run:
          name: pull docker image
          command: docker pull $IMAGE:latest
      - run:
          name: build docker image
          command: docker build --tag $IMAGE:latest --file ./Dockerfile.prod .
      - run:
          name: push docker image
          command: docker push $IMAGE:latest
      # test
      - run:
          name: build docker-compose
          command: |
              set -x
              docker-compose up -d
      - run:
          name: Run test and formatter
          command: |
              docker-compose exec users python -m pytest "project/tests" -p no:warnings
              docker-compose exec users flake8 project
              docker-compose exec users black project --check
              docker-compose exec users isort project/**/*.py --check-only
      # deploy
      - run:
          name: setup environment
          command: |
              chmod +x ./release.sh
      - run:
          name: build docker image
          command: docker build --tag $IMAGE --file ./Dockerfile.prod .
      - run:
          name: heloku login
          command:
              docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
      - run:
          name: push docker image and release
          command: |
              docker push $IMAGE
              ./release.sh